### PR TITLE
Add check on null for stylesXMLFilePath property

### PR DESCRIPTION
**Pull request by reznikartem**
Add check on null for stylesXMLFilePath property in getNumberFormatCode method of XLSX Reader StyleManager

### CODE REVIEW

**Comment by Slamdunk** [comment]
Hi, can you add a test that shows when and how this happens please?

**Comment by reznikartem** [comment]
Example of file for reproducing error:

[broken.xlsx](https://github.com/user-attachments/files/15863576/broken.xlsx)

Code:

```
$reader = new OpenSpout\Reader\XLSX\Reader();
$reader->open("path/to/broken.xlsx");
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        $cells = $row->getCells();
    }
}
```

And here occured error:

```
Fatal error:  Uncaught TypeError: OpenSpout\Reader\Wrapper\XMLReader::openFileInZip(): Argument #2 ($fileInsideZipPath) must be of type string, null given, called in /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/Manager/StyleManager.php on line 154 and defined in /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/Wrapper/XMLReader.php:27
--
  | Stack trace:
  | #0 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/Manager/StyleManager.php(154): OpenSpout\Reader\Wrapper\XMLReader->openFileInZip('/usr/local/www/...', NULL)
  | #1 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/Manager/StyleManager.php(138): OpenSpout\Reader\XLSX\Manager\StyleManager->extractRelevantInfo()
  | #2 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/Manager/StyleManager.php(106): OpenSpout\Reader\XLSX\Manager\StyleManager->getStylesAttributes()
  | #3 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/Helper/CellValueFormatter.php(201): OpenSpout\Reader\XLSX\Manager\StyleManager->getNumberFormatCode(0)
  | #4 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/Helper/CellValueFormatter.php(117): OpenSpout\Reader\XLSX\Helper\CellValueFormatter->formatNumericCellValue('0', 0)
  | #5 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/RowIterator.php(323): OpenSpout\Reader\XLSX\Helper\CellValueFormatter->extractAndFormatNodeValue(Object(DOMElement))
  | #6 [internal function]: OpenSpout\Reader\XLSX\RowIterator->processCellStartingNode(Object(OpenSpout\Reader\Wrapper\XMLReader))
  | #7 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/Common/XMLProcessor.php(151): ReflectionMethod->invokeArgs(Object(OpenSpout\Reader\XLSX\RowIterator), Array)
  | #8 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/Common/XMLProcessor.php(71): OpenSpout\Reader\Common\XMLProcessor->invokeCallback(Array, Array)
  | #9 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/RowIterator.php(262): OpenSpout\Reader\Common\XMLProcessor->readUntilStopped()
  | #10 /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/XLSX/RowIterator.php(176): OpenSpout\Reader\XLSX\RowIterator->readDataForNextRow()
  | #11 /usr/local/www_test/API/TEST/lcab/test5.php(36): OpenSpout\Reader\XLSX\RowIterator->next()
  | #12 {main}
  | thrown in /usr/local/www_test/Core/vendor/openspout/openspout/src/Reader/Wrapper/XMLReader.php on line <b>27
```

**Comment by Slamdunk** [comment]
Yeah, I mean can you add an automated test in the code base?

**Comment by reznikartem** [comment]
> Yeah, I mean can you add an automated test in the code base?

@Slamdunk I`m added automated test and fix Coding Standards issues

**Review by Slamdunk — APPROVED** [review]
Thank you :muscle:

**Pull request merged**
