### PR TITLE
Fix for incorrect PHP date format when including \T in xlsx date formats

### LINKED ISSUE #129: XLSX date format incorrect when including escaped characters
I have an XLSX file with dates formatted: 
yyyy\-mm\-dd\Thh:mm:ss

This is incorrectly converted to a PHP date format: 
Y-m-dtH:i:s

The lowercase t should be maintained as an escaped uppercase T, like this: 
\T

The code producing this comes from here:
https://github.com/openspout/openspout/blob/e236da4d3ba365b6fb35803233a6f938497ca496/src/Reader/XLSX/Helper/DateFormatHelper.php#L82
https://github.com/openspout/openspout/blob/e236da4d3ba365b6fb35803233a6f938497ca496/src/Reader/XLSX/Helper/DateFormatHelper.php#L85

### PR DESCRIPTION
**Pull request by harry-ybim**
With this pull request the date format from XLSX files can support \T. It may be better to account for any and all other potential escaped characters that we want to maintain in the PHP date format, for now this achieves what I needed for an ISO 8601 compatible date format at least.

### CODE REVIEW

**Comment by Slamdunk** [comment]
Hi, can you add tests please?
You can run `make` locally to have the build feedbacks needed for CI to pass

**Comment by Slamdunk** [comment]
@harry-huddle you've pushed much more than what the PR title originally intended to fix, could you please split different fix/features in different PRs?

**Comment by harry-huddle** [comment]
> @harry-huddle you've pushed much more than what the PR title originally intended to fix, could you please split different fix/features in different PRs?

I can honestly say I have no idea what I'm doing with this as a forked repo, I only work on private repos on Bitbucket usually. Given that the main repo has been updated I was trying to bring my forked repo up to date with that, I'm guessing that wasn't the correct thing to do?

**Comment by Slamdunk** [comment]
Many commits of this PR have been already merged in previous PRs of yours: https://github.com/openspout/openspout/commits?author=jverelst

Then you added only here more commits regarding styles, and the fix for the PR title.

I suggest you to check `4.x` branch out, pull the upstream commits, and rebase this PR ont it, discarding all the commits that have already been merged.

Then split the styles edits from the date fix, and open two distinct PR.

**Pull request closed without merging**
