### PR TITLE
[XLSX] Add mergeCells reader

### PR DESCRIPTION
**Pull request by karakum**
Add possibility to read MergeCells metadata from XLSX sheet data xml.

### CODE REVIEW

**Comment by Slamdunk** [comment]
Hi, can you add a test please?

**Comment by karakum** [comment]
@Slamdunk tests arrived!

**Comment by karakum** [comment]
@Slamdunk it is seems that need your attention

```
[2024-09-19T18:32:25.169Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 2467s.', code='throttled')}
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v2.1.0/dist/codecov' failed with exit code 255
```

**Comment by Slamdunk** [comment]
Thank you but `3.x` branch has been EOLed

**Pull request closed without merging**
