### PR TITLE
fix: duplicate xlsx files on Windows

### LINKED ISSUE #85: styles.xml and workbook.xml are added twice to the archive on Windows
Using PHP 8.1.5 and OpenSpout 4.6.2 on Windows 10.

addFileToArchiveWithCompressionMethod() adds "xl\workbook.xml" and "xl\styles.xml"
then addFolderToArchive() re-adds them as "xl/workbook.xml" and "xl/styles.xml"
Notice the different directory separators.

$zip->locateName() in shouldSkipFile() fails to see them as duplicates and they are not overwritten either. The files end up in the zip archive twice. The end result is that at least Excel 2010 says that the file is corrupt (but is able to repair it). And of course the file is bigger than it should be.

I upgraded to OpenSpout from an older Spout 2.x, where this issue didn't exist. So then I noticed that if I revert this change in the FileSystemHelper.php, everything works fine again:

```
$this->zipHelper->addFileToArchive($zip, $this->rootFolder, self::XL_FOLDER_NAME.\DIRECTORY_SEPARATOR.self::WORKBOOK_XML_FILE_NAME);
$this->zipHelper->addFileToArchive($zip, $this->rootFolder, self::XL_FOLDER_NAME.\DIRECTORY_SEPARATOR.self::STYLES_XML_FILE_NAME);
```
=>

```
$this->zipHelper->addFileToArchive($zip, $this->rootFolder, self::XL_FOLDER_NAME . '/' . self::WORKBOOK_XML_FILE_NAME);
$this->zipHelper->addFileToArchive($zip, $this->rootFolder, self::XL_FOLDER_NAME . '/' . self::STYLES_XML_FILE_NAME);
```

### PR DESCRIPTION
**Pull request by sutrik**
fix #85

### CODE REVIEW

**Comment by Slamdunk** [comment]
Hi, thank you for the contribution. Can you also add some test for the bug so we are sure it never gets reintroduced in the future?

**Comment by sutrik** [comment]
> Hi, thank you for the contribution. Can you also add some test for the bug so we are sure it never gets reintroduced in the future?

Sure, I'll look into it.

**Comment by sutrik** [comment]
I decided to do the fix in a different way. Otherwise making a test would have required creating interfaces for FileSystemHelper and ZipHelper just so they could have been mocked.

**Review by Slamdunk — APPROVED** [review]

**Comment by Slamdunk** [comment]
Thank you @sutrik

**Pull request merged**
